#服务启动端口
server :
  port :  8000

#数据库配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  redis:
    # 地址
    host: 121.196.246.85
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: pp123456
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# Mybatis mapper 映射路径配置
mybatis:
  type-aliases-package: com.lasting.mapper
  mapper-locations: classpath*:mapper/*Mapping.xml


# 日志输出
logging:
  level:
    com.example.sql_demo: debug
    org.springframework: warn
  file:
    name: /Users/quepengbiao/logs

task:
  cron: 0 0/5 * * * ?

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql


